variables:
  DOCKER_DRIVER: overlay2

dco_check:
  image: python:3
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_EXTERNAL_PULL_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    - python3 dco_check.py --verbose
