branches:
  only:
    - master

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
dist: bionic
install:
  - pip install -U pytest pytest-cov pytest-repeat
  - pip install -U flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes pep8-naming pylint
  - pip install -U mypy
  - pip install -U codecov
script:
  - python3 -m pytest --cov=dco_check --cov-branch --cov-report=xml
  - codecov
  - python3 dco_check/dco_check.py --verbose
