# action.yml
name: 'DCO check'
description: 'A reusable action that checks that all commits for a proposed change are signed off'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Check DCO
      run: python ${{ github.action_path }}/dco_check.py
      shell: bash
