# action.yml
name: 'Check DCO Signoff'
description: 'A reusable action that checks if all commit has a DCO signoff'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Run Python script
      run: python ${{ github.action_path }}/dco_check.py
      shell: bash
