trigger:
- master
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      pip install -U pytest pytest-cov pytest-repeat
      pip install -U flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes pep8-naming pylint
      pip install -U mypy
      pip install -U codecov
    displayName: 'Install test dependencies'
  - script: |
      python -m pytest --cov=dco_check --cov-branch --cov-report=xml
    displayName: 'Run tests'
  - script: |
      codecov
    displayName: 'Upload coverage'
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
  - script: |
      python dco_check/dco_check.py --verbose
    displayName: 'Check DCO'
- job: Windows
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      pip install -U pytest pytest-cov pytest-repeat
      pip install -U flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes pep8-naming pylint
      pip install -U mypy
      pip install -U codecov
    displayName: 'Install test dependencies'
  - script: |
      python -m pytest --cov=dco_check --cov-branch --cov-report=xml
    displayName: 'Run tests'
  - script: |
      codecov
    displayName: 'Upload coverage'
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
  - script: |
      python dco_check/dco_check.py --verbose
    displayName: 'Check DCO'
